<?php
// $Id$

/**
* Implementation of hook_field_formatter_info().
*/
function filefieldmp3playerwithdownload_field_formatter_info() {
  $formatters = array();
  $players = mp3player_players();

  foreach($players as $name => $player) {
    $formatters['mp3playerwithdownload_'. $player['name']] = array(
      'label' => t('MP3 Player with download ('.$player['name'].')'),
      'field types' => array('filefield')
    );
  }

  return $formatters;
}

/**
 * Implementation of hook_theme().
 */
function filefieldmp3playerwithdownload_theme() {
  $path = drupal_get_path('module', 'filefieldmp3playerwithdownload') .'/theme';
  $theme = array();
  $players = mp3player_players();

  foreach($players as $name => $player) {
    $theme['filefieldmp3playerwithdownload_formatter_mp3playerwithdownload_'. $player['name']] = array(
      'arguments' => array('element' => NULL),
      'function' => 'theme_filefieldmp3playerwithdownload_formatter_mp3player',
    );
  }
  
  $theme['filefieldmp3playerwithdownload_description'] = array(
    'template' => 'description',
    'arguments' => array(
      'title' => NULL,
      'artist' => NULL,
      'album' => NULL,
      'year' => NULL,
      'track' => NULL,
      'genre' => NULL,
    ),
    'path' => $path,
    );
  return $theme;
}

/**
 * Formatter theme function for file fields presented as a Flash MP3 Player.
 */
function theme_filefieldmp3playerwithdownload_formatter_mp3player($element) {
  $item = $element['#item'];
  if($item['list'] == "0") {
    // Isn't listed so bail now
    return;
  }
  
  if(variable_get('mp3player_description', 'description') == 'id3' && module_exists(getid3) && getid3_load() == TRUE) {
    $info = getid3_analyze($item['filepath']);

    $title = $info['tags']['id3v2']['title'][0];
    $artist = $info['tags']['id3v2']['artist'][0];
    $album = $info['tags']['id3v2']['album'][0];
    $year = $info['tags']['id3v2']['year'][0];
    $track = $info['tags']['id3v2']['track'][0];
    $genre = $info['tags']['id3v2']['genre'][0];
    
    $description = theme('filefieldmp3playerwithdownload_description', $title, $artist, $album, $year, $track, $genre);
  }
  else if(isset($item['data']['description']) && is_array($item['data'])) {
    //Data straight from node isn't serialized
    $description = $item['data']['description'];
  }
  else if(isset($item['data']['description']) && is_array(unserialize($item['data']))){
    //Data from a View is on the other hand
    $bits = unserialize($item['data']);
    $description = $bits['description'];
  }
  
  $parts = explode('_', $element['#formatter']);
  unset($parts[0]);
  $player = implode('_', $parts);

   $element['#item']['data']['description'] = t("Deskarga");
  if (!empty($item['filepath'])) {
    if($item['filemime'] == 'audio/mpeg' || $item['filemime'] == 'audio/x-mpeg' || $item['filemime'] == 'audio/mp3' || $item['filemime'] == 'audio/x-mp3' || $item['filemime'] == 'audio/mpeg3' || $item['filemime'] == 'audio/x-mpeg3' || $item['filemime'] == 'audio/mpg' || $item['filemime'] == 'audio/x-mpg' || $item['filemime'] == 'audio/mpegaudi') {
      //MP3 files get special treatment.
      $output = theme('mp3player', $player, base_path().$item['filepath'], NULL, NULL, $description);
      $output .= theme('filefield_formatter_default', $element);
      return $output;
    }
    else {
      // Fall back to filefield's default behavior.
      return theme('filefield_formatter_default', $element);
    }
  }
}